services:
  code-server:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
      - "5000:5000"
      - "5001:5001"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PASSWORD=${SERVICE_PASSWORD_64_PASSWORDCODESERVER}
      - SUDO_PASSWORD=${SERVICE_PASSWORD_SUDOCODESERVER}
    volumes:
      - './workspace:/home/coder/workspace'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 30s
      timeout: 10s
      retries: 3
