services:
  code-server:
    image: 'lscr.io/linuxserver/code-server:latest'
    environment:
      - SERVICE_FQDN_CODESERVER_8443
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - PASSWORD=$SERVICE_PASSWORD_64_PASSWORDCODESERVER
      - SUDO_PASSWORD=$SERVICE_PASSWORD_SUDOCODESERVER
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - 'code-server-config:/config'
      - './workspace:/home/coder/workspace'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8443'
      interval: 2s
      timeout: 10s
      retries: 15
